

% Q3
speed = 250; staticTemperature = 283.15;...
    cP = 1.004; gamma = 1.4;...
    piC = 16; eta = 0.88;...
    fluidName = 'air';
Tt3 = CompressorTotalTemperature(IsentropicTemp(staticTemperature,...
    MachNumber(speed,staticTemperature,12)),piC,fluidName,eta)
